version: '2.1'
services:

  nginx:
    container_name: Test_Nginx
    image: nginx:1.13.8-alpine
    ports:
      - 8080:80
    links:
      - test
    volumes:
      - web:/app/public
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

  test:
    container_name: Test
    build: .
    volumes:
      - web:/app/public

volumes:
  web:
